---
title: "Gov 50 Final Project"
author: Mary Catherine
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I will be using the Chicago Health Data for my final project. My research question will be: How does elevated blood lead levels correspond with success outcomes for different neighborhoods in Chicago?
My hypothesis is that when blood lead levels are higher, the income, graduation rate, and health outcomes for people in that neighborhood will be lower. I believe this will occur because high lead levels are correlated with low-income housing, and can lead to lower iq scores in children.  
My explanatory variable is the blood lead level of children in any particular neighborhood.  
My outcome variables of interest are income, high school graduation rate, and iq. 


The observed pattern in the data that would support my hypothesis is that there would be a negative correlation between the blood lead count in children and and income, graduation rate, and iq. If those two variables had a positive relationship, than my hypothesis would be disproved. 


I will be using the variables Inc_21 and EDB_21 for now for the outcome information I will be using LDPC_22 for the blood lead levels. This way I will also be able to track how the outcome from my analysis changes between outcomes 


# Loading data 

```{r}

library(readr)
library(ggplot2)
Chicago_Health_Data_ <- read_csv("Chicago Health Data .csv")
Chicago_Health_Data_$LDPC_22 <- as.numeric(Chicago_Health_Data_$LDPC_22)
Chicago_Health_Data_$EDB_21 <- as.numeric(Chicago_Health_Data_$EDB_21)

max_LDPC <- max(Chicago_Health_Data_$LDPC_22, na.rm = TRUE)
max_EDB <- max(Chicago_Health_Data_$EDB_21, na.rm = TRUE)


plot_1 <- ggplot(Chicago_Health_Data_, aes(x = EDB_21, y = LDPC_22)) + 
  geom_point() + 
  labs( x = "High School Graduation rate(%)",
        y = "Number of children aged 1-5 with peak annual blood lead level(µg/dL) ", 
        title = "Relationship between lead exposure and high school graduation rates") +
scale_y_continuous(breaks = seq(0, ceiling(max_LDPC), by = 5)) +
  scale_x_continuous(breaks = seq(0, ceiling(max_EDB), by = 5))

plot_1

```

# Showing correlation between 